name: Deploy FastAPI App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./"
          target: "/home/azureuser/app"
          rm: true

      - name: Deploy Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Install dependencies
            sudo apt-get update -y
            sudo apt-get install -y python3 python3-pip

            # Setup virtual environment
            cd /home/azureuser/app
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # Create Systemd service file
            sudo bash -c 'cat > /etc/systemd/system/fastapi.service <<EOF
            [Unit]
            Description=FastAPI Service
            After=network.target

            [Service]
            User=azureuser
            WorkingDirectory=/home/azureuser/app
            ExecStart=/home/azureuser/app/venv/bin/uvicorn main:app --host 0.0.0.0 --port 80
            Restart=always

            [Install]
            WantedBy=multi-user.target
            EOF'

            # Reload and start the service
            sudo chmod 644 /etc/systemd/system/fastapi.service
            sudo systemctl daemon-reload
            sudo systemctl enable fastapi.service
            sudo systemctl restart fastapi.service

            # Debugging
            sudo systemctl status fastapi.service || true
            journalctl -u fastapi.service -n 50 --no-pager
